// Données pour le dashboard appartement
// Ces données sont chargées au démarrage si localStorage est vide

// Données pour le mode ACHAT
const sampleDataAchat = [
    {
        id: 1,
        quartier: "Centre-ville",
        type: "T2",
        prix: 125000,
        surface: 45,
        pieces: 2,
        dpe: "D",
        chauffage: "Électrique",
        charges: 1200,
        parking: true,
        cave: true,
        terrasse: false,
        clim: false,
        ascenseur: true,
        balcon: false,
        etat: "À voir",
        datePublication: "2024-01-15",
        dateContact: "2024-01-16",
        dateVisite: "2024-01-20",
        contact: "Agence Immo Sud",
        tel: "04 67 00 00 00",
        adresse: "12 Rue de la République",
        siteWeb: "https://www.example.com/bien1",
        notes: "Bien situé, proche commerces. Cuisine à refaire."
    },
    {
        id: 2,
        quartier: "Antigone",
        type: "T3",
        prix: 185000,
        surface: 65,
        pieces: 3,
        dpe: "C",
        chauffage: "Gaz",
        charges: 1500,
        parking: false,
        cave: true,
        terrasse: true,
        clim: false,
        ascenseur: true,
        balcon: false,
        etat: "Vu",
        datePublication: "2024-01-10",
        dateContact: "2024-01-11",
        dateVisite: "2024-01-18",
        contact: "Propriétaire",
        tel: "06 12 34 56 78",
        adresse: "Bâtiment C3, Avenue Picasso",
        siteWeb: "",
        notes: "Quartier calme, architecture moderne. Terrasse de 12m²."
    },
    {
        id: 3,
        quartier: "Comédie",
        type: "T2",
        prix: 165000,
        surface: 50,
        pieces: 2,
        dpe: "E",
        chauffage: "Électrique",
        charges: 900,
        parking: false,
        cave: false,
        terrasse: false,
        clim: false,
        ascenseur: false,
        balcon: true,
        etat: "Retenu",
        datePublication: "2024-01-12",
        dateContact: "2024-01-13",
        dateVisite: "2024-01-19",
        contact: "Agence Centre",
        tel: "04 67 11 11 11",
        adresse: "8 Rue de la Loge",
        siteWeb: "https://www.example.com/bien3",
        notes: "Emplacement idéal, balcon donnant cour intérieure. Travaux à prévoir."
    },
    {
        id: 4,
        quartier: "Ecusson",
        type: "Studio",
        prix: 95000,
        surface: 25,
        pieces: 1,
        dpe: "F",
        chauffage: "Électrique",
        charges: 600,
        parking: false,
        cave: false,
        terrasse: false,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Refusé",
        datePublication: "2024-01-08",
        dateContact: "2024-01-09",
        dateVisite: "2024-01-15",
        contact: "Agence Vieux",
        tel: "04 67 22 22 22",
        adresse: "3 Rue Jean-Jaurès",
        siteWeb: "",
        notes: "Trop petit, mauvaise isolation thermique. DPE défavorable."
    },
    {
        id: 5,
        quartier: "Port Marianne",
        type: "T4",
        prix: 245000,
        surface: 85,
        pieces: 4,
        dpe: "B",
        chauffage: "Pompe à chaleur",
        charges: 1800,
        parking: true,
        cave: true,
        terrasse: true,
        clim: true,
        ascenseur: true,
        balcon: false,
        etat: "À voir",
        datePublication: "2024-01-18",
        dateContact: "2024-01-19",
        dateVisite: "",
        contact: "Promoteur Neuf",
        tel: "04 67 33 33 33",
        adresse: "Rue de Berlin",
        siteWeb: "https://www.example.com/bien5",
        notes: "Neuf, label BBC. Terrasse de 20m². Parking inclus."
    },
    {
        id: 6,
        quartier: "Coursan",
        type: "Duplex",
        prix: 195000,
        surface: 75,
        pieces: 4,
        dpe: "C",
        chauffage: "Bois",
        charges: 800,
        parking: true,
        cave: true,
        terrasse: false,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Vu",
        datePublication: "2024-01-14",
        dateContact: "2024-01-15",
        dateVisite: "2024-01-21",
        contact: "Propriétaire",
        tel: "06 98 76 54 32",
        adresse: "15 Avenue de la Mairie",
        siteWeb: "",
        notes: "Duplex T4, bien agencé. Chauffage bois économique. Quartier calme."
    },
    {
        id: 7,
        quartier: "Beaux-Arts",
        type: "T3",
        prix: 210000,
        surface: 60,
        pieces: 3,
        dpe: "D",
        chauffage: "Gaz",
        charges: 1400,
        parking: false,
        cave: true,
        terrasse: false,
        clim: false,
        ascenseur: true,
        balcon: true,
        etat: "Retenu",
        datePublication: "2024-01-16",
        dateContact: "2024-01-17",
        dateVisite: "2024-01-22",
        contact: "Agence Artistes",
        tel: "04 67 44 44 44",
        adresse: "22 Rue des Écoles",
        siteWeb: "https://www.example.com/bien7",
        notes: "Quartier étudiant, proche tram. Hauts plafonds, moulures."
    },
    {
        id: 8,
        quartier: "Polygone",
        type: "T2",
        prix: 140000,
        surface: 48,
        pieces: 2,
        dpe: "E",
        chauffage: "Électrique",
        charges: 1100,
        parking: false,
        cave: false,
        terrasse: false,
        clim: false,
        ascenseur: true,
        balcon: false,
        etat: "Refusé",
        datePublication: "2024-01-11",
        dateContact: "2024-01-12",
        dateVisite: "2024-01-17",
        contact: "Agence Commerciale",
        tel: "04 67 55 55 55",
        adresse: "Boulevard d'Occitanie",
        siteWeb: "",
        notes: "Trop bruyant, orientation Nord. Prix au m² élevé."
    },
    {
        id: 9,
        quartier: "Figuerolles",
        type: "T3",
        prix: 155000,
        surface: 62,
        pieces: 3,
        dpe: "D",
        chauffage: "Collectif",
        charges: 1300,
        parking: true,
        cave: true,
        terrasse: false,
        clim: false,
        ascenseur: true,
        balcon: true,
        etat: "À voir",
        datePublication: "2024-01-19",
        dateContact: "2024-01-20",
        dateVisite: "",
        contact: "Agence Nord",
        tel: "04 67 66 66 66",
        adresse: "Avenue de Figuerolles",
        siteWeb: "https://www.example.com/bien9",
        notes: "Quartier résidentiel, proche écoles. Parking privatif."
    },
    {
        id: 10,
        quartier: "Gambetta",
        type: "T4",
        prix: 225000,
        surface: 80,
        pieces: 4,
        dpe: "C",
        chauffage: "Gaz",
        charges: 1600,
        parking: true,
        cave: true,
        terrasse: false,
        clim: false,
        ascenseur: true,
        balcon: true,
        etat: "Vu",
        datePublication: "2024-01-13",
        dateContact: "2024-01-14",
        dateVisite: "2024-01-20",
        contact: "Agence Gambetta",
        tel: "04 67 77 77 77",
        adresse: "Boulevard Gambetta",
        siteWeb: "",
        notes: "Appartement lumineux, balcon traversant. Bon plan."
    }
];

// =============================================================================
// DONNÉES DE TEST (CONSERVÉES POUR RÉFÉRENCE)
// =============================================================================
/*
const sampleDataLocation = [
    {
        id: 1,
        quartier: "Centre-ville",
        type: "T2",
        loyer: 850,
        charges: 50,
        surface: 45,
        pieces: 2,
        dpe: "D",
        chauffage: "Électrique",
        depotGarantie: 1700,
        parking: true,
        cave: true,
        terrasse: false,
        clim: false,
        ascenseur: true,
        balcon: false,
        etat: "À voir",
        datePublication: "2024-01-15",
        dateContact: "2024-01-16",
        dateVisite: "2024-01-20",
        contact: "Agence Immo Sud",
        tel: "04 67 00 00 00",
        adresse: "12 Rue de la République",
        siteWeb: "https://www.example.com/bien1",
        notes: "Bien situé, proche commerces. Loyer charges comprises."
    },
    {
        id: 2,
        quartier: "Antigone",
        type: "T3",
        loyer: 1200,
        charges: 80,
        surface: 65,
        pieces: 3,
        dpe: "C",
        chauffage: "Gaz",
        depotGarantie: 2400,
        parking: false,
        cave: true,
        terrasse: true,
        clim: false,
        ascenseur: true,
        balcon: false,
        etat: "Vu",
        datePublication: "2024-01-10",
        dateContact: "2024-01-11",
        dateVisite: "2024-01-18",
        contact: "Propriétaire",
        tel: "06 12 34 56 78",
        adresse: "Bâtiment C3, Avenue Picasso",
        siteWeb: "",
        notes: "Quartier calme, architecture moderne. Terrasse de 12m²."
    },
    {
        id: 3,
        quartier: "Comédie",
        type: "T2",
        loyer: 950,
        charges: 60,
        surface: 50,
        pieces: 2,
        dpe: "E",
        chauffage: "Électrique",
        depotGarantie: 1900,
        parking: false,
        cave: false,
        terrasse: false,
        clim: false,
        ascenseur: false,
        balcon: true,
        etat: "Retenu",
        datePublication: "2024-01-12",
        dateContact: "2024-01-13",
        dateVisite: "2024-01-19",
        contact: "Agence Centre",
        tel: "04 67 11 11 11",
        adresse: "8 Rue de la Loge",
        siteWeb: "https://www.example.com/bien3",
        notes: "Emplacement idéal, balcon donnant cour intérieure."
    },
    {
        id: 4,
        quartier: "Ecusson",
        type: "Studio",
        loyer: 550,
        charges: 40,
        surface: 25,
        pieces: 1,
        dpe: "F",
        chauffage: "Électrique",
        depotGarantie: 1100,
        parking: false,
        cave: false,
        terrasse: false,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Refusé",
        datePublication: "2024-01-08",
        dateContact: "2024-01-09",
        dateVisite: "2024-01-15",
        contact: "Agence Vieux",
        tel: "04 67 22 22 22",
        adresse: "3 Rue Jean-Jaurès",
        siteWeb: "",
        notes: "Trop petit, mauvaise isolation thermique."
    },
    {
        id: 5,
        quartier: "Port Marianne",
        type: "T4",
        loyer: 1500,
        charges: 100,
        surface: 85,
        pieces: 4,
        dpe: "B",
        chauffage: "Pompe à chaleur",
        depotGarantie: 3000,
        parking: true,
        cave: true,
        terrasse: true,
        clim: true,
        ascenseur: true,
        balcon: false,
        etat: "À voir",
        datePublication: "2024-01-18",
        dateContact: "2024-01-19",
        dateVisite: "",
        contact: "Promoteur Neuf",
        tel: "04 67 33 33 33",
        adresse: "Rue de Berlin",
        siteWeb: "https://www.example.com/bien5",
        notes: "Neuf, label BBC. Terrasse de 20m². Parking inclus."
    },
    {
        id: 6,
        quartier: "Beaux-Arts",
        type: "T3",
        loyer: 1100,
        charges: 70,
        surface: 60,
        pieces: 3,
        dpe: "D",
        chauffage: "Gaz",
        depotGarantie: 2200,
        parking: false,
        cave: true,
        terrasse: false,
        clim: false,
        ascenseur: true,
        balcon: true,
        etat: "Vu",
        datePublication: "2024-01-16",
        dateContact: "2024-01-17",
        dateVisite: "2024-01-22",
        contact: "Agence Artistes",
        tel: "04 67 44 44 44",
        adresse: "22 Rue des Écoles",
        siteWeb: "https://www.example.com/bien7",
        notes: "Quartier étudiant, proche tram. Hauts plafonds."
    },
    {
        id: 7,
        quartier: "Figuerolles",
        type: "T3",
        loyer: 980,
        charges: 65,
        surface: 62,
        pieces: 3,
        dpe: "D",
        chauffage: "Collectif",
        depotGarantie: 1960,
        parking: true,
        cave: true,
        terrasse: false,
        clim: false,
        ascenseur: true,
        balcon: true,
        etat: "À voir",
        datePublication: "2024-01-19",
        dateContact: "2024-01-20",
        dateVisite: "",
        contact: "Agence Nord",
        tel: "04 67 66 66 66",
        adresse: "Avenue de Figuerolles",
        siteWeb: "https://www.example.com/bien9",
        notes: "Quartier résidentiel, proche écoles. Parking privatif."
    },
    {
        id: 8,
        quartier: "Gambetta",
        type: "T4",
        loyer: 1350,
        charges: 90,
        surface: 80,
        pieces: 4,
        dpe: "C",
        chauffage: "Gaz",
        depotGarantie: 2700,
        parking: true,
        cave: true,
        terrasse: false,
        clim: false,
        ascenseur: true,
        balcon: true,
        etat: "Retenu",
        datePublication: "2024-01-13",
        dateContact: "2024-01-14",
        dateVisite: "2024-01-20",
        contact: "Agence Gambetta",
        tel: "04 67 77 77 77",
        adresse: "Boulevard Gambetta",
        siteWeb: "",
        notes: "Appartement lumineux, balcon traversant. Bon plan."
    }
];
*/

// =============================================================================
// DONNÉES RÉELLES - MODE LOCATION
// Généré depuis data-location-real.json (63 appartements)
// =============================================================================
const sampleDataLocationReal = [
    {
        id: 1,
        quartier: "Beaux-arts",
        type: "T3",
        meublé: false,
        loyer: 992,
        charges: 0,
        charges_annuelles: 0,
        surface: 79,
        pieces: 3,
        dpe: "C",
        chauffage: "Electrique",
        depotGarantie: 992,
        parking: false,
        cave: true,
        terrasse: false,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Rendez-vous visite",
        datePublication: "2026-02-13",
        dateContact: "2026-02-12",
        dateVisite: "2026-02-16",
        contact: "IMMOBIS COMEDIE",
        tel: "0 46 76 03 16 0",
        adresse: "12 Rue Michel Vernière",
        siteWeb: "https://immobilier.lefigaro.fr/annonces/annonce-95209553.html",
        notes: ""
    },
    {
        id: 2,
        quartier: "Boutonnet",
        type: "T3",
        meublé: false,
        loyer: 940,
        charges: 0,
        charges_annuelles: 0,
        surface: 68,
        pieces: 3,
        dpe: "D",
        chauffage: "Gaz",
        depotGarantie: 940,
        parking: false,
        cave: true,
        terrasse: true,
        clim: true,
        ascenseur: false,
        balcon: false,
        etat: "Rendez-vous visite",
        datePublication: "2026-02-12",
        dateContact: "2026-02-12",
        dateVisite: "2026-02-17",
        contact: "Agence Espadon - PUJOL DIANE",
        tel: "0 42 34 76 97 8",
        adresse: "25 Rue Aristide Maillol",
        siteWeb: "https://www.bienici.com/annonce/location/montpellier/appartement/3pieces/hektor-ESPADONIMMO-274724",
        notes: ""
    },
    {
        id: 3,
        quartier: "Centre historique",
        type: "T3",
        meublé: false,
        loyer: 950,
        charges: 0,
        charges_annuelles: 0,
        surface: 68,
        pieces: 3,
        dpe: "C",
        chauffage: "Electrique",
        depotGarantie: 950,
        parking: true,
        cave: false,
        terrasse: false,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "En attente de rappel",
        datePublication: "2026-02-07",
        dateContact: "",
        dateVisite: "",
        contact: "ECUSSON IMMOBILIER - GOGUET CHAPUIS David",
        tel: "0 46 76 04 56 0",
        adresse: "",
        siteWeb: "https://www.bienici.com/annonce/location/montpellier/appartement/3pieces/hektor-ecussonimmobilier-65",
        notes: "Exposé Est Ouest - en attente rappel"
    },
    {
        id: 4,
        quartier: "Aiguelongue",
        type: "T2",
        meublé: false,
        loyer: 774,
        charges: 0,
        charges_annuelles: 0,
        surface: 55,
        pieces: 2,
        dpe: "B",
        chauffage: "Electrique",
        depotGarantie: 774,
        parking: true,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Il faut appeler",
        datePublication: "2026-02-14",
        dateContact: "",
        dateVisite: "",
        contact: "L'AGENCE ROXIM",
        tel: "0 46 56 60 67 3",
        adresse: "",
        siteWeb: "https://www.bienici.com/annonce/ics-rox_ROXIM_loc-GES01230114-483",
        notes: "message vocale"
    },
    {
        id: 5,
        quartier: "Centre historique",
        type: "T3",
        meublé: false,
        loyer: 1000,
        charges: 0,
        charges_annuelles: 0,
        surface: 68,
        pieces: 3,
        dpe: "C",
        chauffage: "Electrique",
        depotGarantie: 1000,
        parking: true,
        cave: true,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Il faut appeler",
        datePublication: "2026-02-14",
        dateContact: "",
        dateVisite: "",
        contact: "",
        tel: "",
        adresse: "",
        siteWeb: "https://www.bienici.com/annonce/location/montpellier/appartement/3pieces/ag341105-513748154",
        notes: "message vocale"
    },
    {
        id: 6,
        quartier: "Figuerolles",
        type: "T3",
        meublé: true,
        loyer: 957,
        charges: 0,
        charges_annuelles: 0,
        surface: 64,
        pieces: 3,
        dpe: "D",
        chauffage: "Electrique",
        depotGarantie: 957,
        parking: false,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Il faut appeler",
        datePublication: "2026-02-05",
        dateContact: "",
        dateVisite: "",
        contact: "L'AGENCE ROXIM",
        tel: "0 46 56 60 67 3",
        adresse: "",
        siteWeb: "https://www.bienici.com/annonce/location/montpellier/appartement/3pieces/ics-rox_ROXIM_loc-GES01610006-483",
        notes: "Exposé Sud - message vocale"
    },
    {
        id: 7,
        quartier: "Centre historique",
        type: "T3",
        meublé: false,
        loyer: 921,
        charges: 0,
        charges_annuelles: 0,
        surface: 61,
        pieces: 3,
        dpe: "D",
        chauffage: "Electrique",
        depotGarantie: 921,
        parking: false,
        cave: false,
        terrasse: false,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Rendez-vous visite",
        datePublication: "2026-02-10",
        dateContact: "",
        dateVisite: "2026-02-16",
        contact: "IMMOBIS LOCATIONS",
        tel: "0 46 54 10 57 9",
        adresse: "",
        siteWeb: "https://www.bienici.com/annonce/location/montpellier/appartement/3pieces/adapt-immo-343732488",
        notes: "Exposé Ouest"
    },
    {
        id: 8,
        quartier: "Centre historique",
        type: "T2",
        meublé: true,
        loyer: 850,
        charges: 0,
        charges_annuelles: 0,
        surface: 56,
        pieces: 2,
        dpe: "D",
        chauffage: "Electrique",
        depotGarantie: 850,
        parking: false,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "En attente de rappel",
        datePublication: "2026-02-12",
        dateContact: "2026-02-12",
        dateVisite: "",
        contact: "",
        tel: "",
        adresse: "",
        siteWeb: "https://www.paruvendu.fr/immobilier/location/appartement/1287937501A1KILHAP000",
        notes: "Réf. annonce WI176704061 - pas du mu, mail envoyé depuis le site"
    },
    {
        id: 9,
        quartier: "Centre historique",
        type: "T3",
        meublé: true,
        loyer: 980,
        charges: 0,
        charges_annuelles: 0,
        surface: 63,
        pieces: 3,
        dpe: "C",
        chauffage: "Electrique",
        depotGarantie: 980,
        parking: false,
        cave: false,
        terrasse: false,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Refusé",
        datePublication: "2026-02-04",
        dateContact: "",
        dateVisite: "",
        contact: "Elsa (particulier)",
        tel: "",
        adresse: "",
        siteWeb: "https://gensdeconfiance.com/fr/ui/post/realestate__rent/1d19061b-48e9-4541-b780-3e41e6d1c55d?utm_source=jinka&utm_medium=partner&utm_campaign=loc-2022",
        notes: "déjà qq un sur le doss"
    },
    {
        id: 10,
        quartier: "Hopitaux-Facultés",
        type: "T3",
        meublé: false,
        loyer: 984,
        charges: 0,
        charges_annuelles: 0,
        surface: 63,
        pieces: 3,
        dpe: "A",
        chauffage: "Electrique",
        depotGarantie: 984,
        parking: true,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Rendez-vous visite",
        datePublication: "2026-02-11",
        dateContact: "2026-02-12",
        dateVisite: "2026-05-26",
        contact: "GASCON IMMOBILIER 1989 - GASCON IMMOBILIER DEPUIS 1989",
        tel: "0 42 34 71 46 5",
        adresse: "439 Rue René Etiemble",
        siteWeb: "https://www.bienici.com/annonce/adapt-immo-34785206",
        notes: ""
    },
    {
        id: 11,
        quartier: "Gares",
        type: "T3",
        meublé: true,
        loyer: 774,
        charges: 0,
        charges_annuelles: 0,
        surface: 49,
        pieces: 3,
        dpe: "D",
        chauffage: "Electrique",
        depotGarantie: 774,
        parking: false,
        cave: true,
        terrasse: false,
        clim: true,
        ascenseur: false,
        balcon: false,
        etat: "Refusé",
        datePublication: "2026-02-15",
        dateContact: "",
        dateVisite: "",
        contact: "ERA LANGUEDOC IMMOBILIER - Mathieu CUILLIER",
        tel: "0 46 54 12 23 1",
        adresse: "",
        siteWeb: "https://www.bienici.com/annonce/location/montpellier/appartement/3pieces/era-2-4589339/contact",
        notes: ""
    },
    {
        id: 12,
        quartier: "Centre historique",
        type: "T2",
        meublé: false,
        loyer: 758,
        charges: 0,
        charges_annuelles: 0,
        surface: 47,
        pieces: 2,
        dpe: "E",
        chauffage: "Electrique",
        depotGarantie: 758,
        parking: false,
        cave: false,
        terrasse: false,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "En attente de rappel",
        datePublication: "2026-02-07",
        dateContact: "",
        dateVisite: "",
        contact: "ecusson immobilier",
        tel: "",
        adresse: "",
        siteWeb: "https://www.ecussonimmobilier.com/631-f2-renove.html",
        notes: "contact via le site car pas numéro"
    },
    {
        id: 13,
        quartier: "Centre historique",
        type: "T2",
        meublé: true,
        loyer: 850,
        charges: 0,
        charges_annuelles: 0,
        surface: 52,
        pieces: 2,
        dpe: "E",
        chauffage: "Electrique",
        depotGarantie: 850,
        parking: false,
        cave: false,
        terrasse: false,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Refusé",
        datePublication: "2026-02-04",
        dateContact: "",
        dateVisite: "",
        contact: "IMMOVANCE",
        tel: "0 60 73 50 53 8",
        adresse: "",
        siteWeb: "https://immobilier.lefigaro.fr/annonces/annonce-97135855.html",
        notes: "joli mais dossier déjà pris"
    },
    {
        id: 14,
        quartier: "La Chambrete",
        type: "T2",
        meublé: true,
        loyer: 889,
        charges: 0,
        charges_annuelles: 0,
        surface: 53,
        pieces: 2,
        dpe: "C",
        chauffage: "Electrique",
        depotGarantie: 889,
        parking: false,
        cave: false,
        terrasse: true,
        clim: true,
        ascenseur: false,
        balcon: false,
        etat: "Contacté",
        datePublication: "2026-02-04",
        dateContact: "2026-02-12",
        dateVisite: "",
        contact: "",
        tel: "",
        adresse: "205 Rue de Fontcarrade",
        siteWeb: "https://www.bienici.com/annonce/location/montpellier/appartement/2pieces/ag340989-510762368",
        notes: "Exposé Sud vue boisée"
    },
    {
        id: 15,
        quartier: "Centre historique",
        type: "T2",
        meublé: false,
        loyer: 793,
        charges: 0,
        charges_annuelles: 0,
        surface: 47,
        pieces: 2,
        dpe: "E",
        chauffage: "Electrique",
        depotGarantie: 793,
        parking: false,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Rendez-vous visite",
        datePublication: "2026-02-11",
        dateContact: "2026-02-12",
        dateVisite: "2026-02-17",
        contact: "ARTIS IMMO",
        tel: "0 46 54 13 03 7",
        adresse: "",
        siteWeb: "https://www.bienici.com/annonce/location/montpellier/appartement/2pieces/adapt-immo-3473711315",
        notes: ""
    },
    {
        id: 16,
        quartier: "Gambetta",
        type: "T2",
        meublé: true,
        loyer: 692,
        charges: 0,
        charges_annuelles: 0,
        surface: 41,
        pieces: 2,
        dpe: "D",
        chauffage: "Electrique",
        depotGarantie: 692,
        parking: false,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Contacté",
        datePublication: "2026-02-11",
        dateContact: "2026-02-12",
        dateVisite: "",
        contact: "",
        tel: "0 46 70 26 60 5",
        adresse: "21 Bd Renouvier",
        siteWeb: "https://www.orpi.com/annonce-location-appartement-t1-montpellier-34000-5e44740d-0ffe-424e-b79f-9dbca52dda4a/",
        notes: "Visale ok. répondre mail avec dossier"
    },
    {
        id: 17,
        quartier: "Les Cevennes",
        type: "T2",
        meublé: false,
        loyer: 850,
        charges: 0,
        charges_annuelles: 0,
        surface: 50,
        pieces: 2,
        dpe: "E",
        chauffage: "Gaz",
        depotGarantie: 850,
        parking: false,
        cave: false,
        terrasse: false,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Contacté",
        datePublication: "2026-02-06",
        dateContact: "2026-02-12",
        dateVisite: "",
        contact: "NEGOCE HABITAT - GARCIA Séverine",
        tel: "0 46 54 15 16 8",
        adresse: "2 Rue des Terebinthes",
        siteWeb: "https://www.bienici.com/annonce/location/montpellier/appartement/2pieces/hektor-negocehabitat-3190",
        notes: "Exposition Sud et Ouest - maisonette"
    },
    {
        id: 18,
        quartier: "Centre historique",
        type: "T2",
        meublé: true,
        loyer: 922,
        charges: 0,
        charges_annuelles: 0,
        surface: 54,
        pieces: 2,
        dpe: "C",
        chauffage: "Electrique",
        depotGarantie: 922,
        parking: false,
        cave: false,
        terrasse: false,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "En attente de rappel",
        datePublication: "2026-02-11",
        dateContact: "2026-02-12",
        dateVisite: "",
        contact: "IMMOBIS LOCATIONS",
        tel: "0 46 54 10 57 9",
        adresse: "29-31 Grand Rue Jean Moulin",
        siteWeb: "https://www.bienici.com/annonce/adapt-immo-343738872",
        notes: "En attente rendez-vous avec locataire"
    },
    {
        id: 19,
        quartier: "Boutonnet",
        type: "T3",
        meublé: false,
        loyer: 915,
        charges: 0,
        charges_annuelles: 0,
        surface: 53,
        pieces: 3,
        dpe: "D",
        chauffage: "Electrique",
        depotGarantie: 915,
        parking: true,
        cave: true,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "En attente de rappel",
        datePublication: "2026-02-12",
        dateContact: "2026-02-12",
        dateVisite: "",
        contact: "HABITAT CONCEPT IMMO",
        tel: "0 46 56 60 00 7",
        adresse: "662 Av. de la Justice de Castelnau",
        siteWeb: "https://www.bienici.com/annonce/adapt-immo-344082776",
        notes: "Expo S. va nous rappeler (loc dedans)"
    },
    {
        id: 20,
        quartier: "Centre historique",
        type: "T2",
        meublé: false,
        loyer: 705,
        charges: 0,
        charges_annuelles: 0,
        surface: 40,
        pieces: 2,
        dpe: "E",
        chauffage: "Electrique",
        depotGarantie: 705,
        parking: false,
        cave: false,
        terrasse: false,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Contacté",
        datePublication: "2026-02-11",
        dateContact: "2026-02-12",
        dateVisite: "",
        contact: "AO Immobilier",
        tel: "0 66 23 19 84 5",
        adresse: "13 Boulevard Pasteur",
        siteWeb: "https://www.jinka.fr/ad/a2102ec3-a6d9-4eca-9d20-72e8aad11ffe?alert_result=4966006599",
        notes: "message vocal laissé"
    },
    {
        id: 21,
        quartier: "Aiguelongue",
        type: "T2",
        meublé: false,
        loyer: 780,
        charges: 0,
        charges_annuelles: 0,
        surface: 44,
        pieces: 2,
        dpe: "A",
        chauffage: "Electrique",
        depotGarantie: 780,
        parking: true,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Refusé",
        datePublication: "2026-02-14",
        dateContact: "",
        dateVisite: "",
        contact: "LACOMBE IMMOBILIER SAS",
        tel: "0 42 34 77 17 8",
        adresse: "",
        siteWeb: "https://www.bienici.com/annonce/location/montpellier/appartement/2pieces/ag340490-511644635",
        notes: "loué"
    },
    {
        id: 22,
        quartier: "Beaux-arts",
        type: "T2",
        meublé: false,
        loyer: 850,
        charges: 0,
        charges_annuelles: 0,
        surface: 47,
        pieces: 2,
        dpe: "D",
        chauffage: "Electrique",
        depotGarantie: 850,
        parking: true,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Refusé",
        datePublication: "2026-02-05",
        dateContact: "2026-02-12",
        dateVisite: "",
        contact: "Agence du courreau - OUCHENE Yanis",
        tel: "",
        adresse: "31bis Av. Saint-Lazare",
        siteWeb: "https://www.bienici.com/annonce/location/montpellier/appartement/2pieces/hektor-AGENCEDUCOURREAU-34000-2958",
        notes: "plus dispo"
    },
    {
        id: 23,
        quartier: "Centre historique",
        type: "T3",
        meublé: true,
        loyer: 790,
        charges: 0,
        charges_annuelles: 0,
        surface: 42,
        pieces: 3,
        dpe: "E",
        chauffage: "Electrique",
        depotGarantie: 790,
        parking: false,
        cave: false,
        terrasse: false,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Contacté",
        datePublication: "2026-02-15",
        dateContact: "2026-02-15",
        dateVisite: "",
        contact: "",
        tel: "0 74 58 86 10 0",
        adresse: "2 Rue du Collège",
        siteWeb: "https://api.jinka.fr/apiv2/alert/redirect_preview?token=7a725e11ce1514ae497ddbdf1eba184a&ad=86952775",
        notes: "boîte vocal robot pas sur de pouvoir avoir quelqu'un au tel"
    },
    {
        id: 24,
        quartier: "Les Cevennes",
        type: "T3",
        meublé: true,
        loyer: 1030,
        charges: 0,
        charges_annuelles: 0,
        surface: 52,
        pieces: 3,
        dpe: "D",
        chauffage: "Electrique",
        depotGarantie: 1030,
        parking: true,
        cave: false,
        terrasse: true,
        clim: true,
        ascenseur: false,
        balcon: false,
        etat: "Il faut appeler",
        datePublication: "2026-02-15",
        dateContact: "2026-02-15",
        dateVisite: "",
        contact: "Agence TER",
        tel: "0 62 55 73 91 6",
        adresse: "",
        siteWeb: "https://www.jinka.fr/ad/3fc4313e-96f4-47ef-aa93-230d53eaa75c?alert_result=4977900706",
        notes: "sms envoyé"
    },
    {
        id: 25,
        quartier: "Antigone",
        type: "T2",
        meublé: false,
        loyer: 919,
        charges: 0,
        charges_annuelles: 0,
        surface: 46,
        pieces: 2,
        dpe: "C",
        chauffage: "Electrique",
        depotGarantie: 919,
        parking: true,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Refusé",
        datePublication: "2026-02-09",
        dateContact: "",
        dateVisite: "",
        contact: "ERA LANGUEDOC IMMOBILIER - Mathieu CUILLIER",
        tel: "0 46 54 12 23 1",
        adresse: "",
        siteWeb: "https://www.bienici.com/annonce/location/montpellier/appartement/2pieces/era-2-15611561",
        notes: "Exposé Sud"
    },
    {
        id: 26,
        quartier: "Lemasson",
        type: "T3",
        meublé: false,
        loyer: 999,
        charges: 0,
        charges_annuelles: 0,
        surface: 111,
        pieces: 3,
        dpe: "E",
        chauffage: "Gaz",
        depotGarantie: 999,
        parking: false,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Contacté",
        datePublication: "2026-02-05",
        dateContact: "2026-02-12",
        dateVisite: "",
        contact: "FDI SERVICES IMMOBILIERS",
        tel: "0 46 54 10 82 9",
        adresse: "56 Av. Georges Clemenceau",
        siteWeb: "https://www.bienici.com/annonce/location/montpellier/appartement/3pieces/netty-fdiservicesimmo-appt-5311",
        notes: ""
    },
    {
        id: 27,
        quartier: "Estanove",
        type: "T4",
        meublé: false,
        loyer: 970,
        charges: 0,
        charges_annuelles: 0,
        surface: 90,
        pieces: 4,
        dpe: "D",
        chauffage: "Electrique",
        depotGarantie: 970,
        parking: true,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Contacté",
        datePublication: "2026-02-12",
        dateContact: "2026-02-12",
        dateVisite: "",
        contact: "NGT",
        tel: "0 46 70 61 30 0",
        adresse: "29 Av. Lepic",
        siteWeb: "https://www.jinka.fr/ad/03745f3c-3d26-4e66-9b94-347c21650980?alert_result=4966314832",
        notes: ""
    },
    {
        id: 28,
        quartier: "Centre historique",
        type: "T3",
        meublé: false,
        loyer: 867,
        charges: 0,
        charges_annuelles: 0,
        surface: 66,
        pieces: 3,
        dpe: "F",
        chauffage: "Electrique",
        depotGarantie: 867,
        parking: false,
        cave: false,
        terrasse: false,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Nouveau",
        datePublication: "2026-02-15",
        dateContact: "",
        dateVisite: "",
        contact: "Foncia Montpellier",
        tel: "0 48 25 30 87 9",
        adresse: "",
        siteWeb: "https://fr.foncia.com/location/montpellier-34/appartement/331621744.htm?utm_source=jinka&utm_medium=app&utm_campaign=test",
        notes: ""
    },
    {
        id: 29,
        quartier: "Estanove",
        type: "T3",
        meublé: false,
        loyer: 850,
        charges: 0,
        charges_annuelles: 0,
        surface: 64,
        pieces: 3,
        dpe: "C",
        chauffage: "Electrique",
        depotGarantie: 850,
        parking: true,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Contacté",
        datePublication: "2026-02-12",
        dateContact: "2026-02-12",
        dateVisite: "",
        contact: "CENTURY 21 Frontignan",
        tel: "0 46 54 11 13 6",
        adresse: "Pass. Armande Béjart, 34070 Montpellier",
        siteWeb: "https://www.bienici.com/annonce/location/montpellier/appartement/3pieces/century-21-202_3322_3800",
        notes: ""
    },
    {
        id: 30,
        quartier: "Ovalie",
        type: "T3",
        meublé: false,
        loyer: 980,
        charges: 0,
        charges_annuelles: 0,
        surface: 73,
        pieces: 3,
        dpe: "D",
        chauffage: "Electrique",
        depotGarantie: 980,
        parking: true,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Contacté",
        datePublication: "2026-02-12",
        dateContact: "2026-02-12",
        dateVisite: "",
        contact: "NGT",
        tel: "0 46 70 61 30 0",
        adresse: "Ovalie",
        siteWeb: "https://www.jinka.fr/ad/a368c40c-f22e-479a-b034-1d6f2117e526?alert_result=4935882612",
        notes: ""
    },
    {
        id: 31,
        quartier: "Ovalie",
        type: "T3",
        meublé: false,
        loyer: 852,
        charges: 0,
        charges_annuelles: 0,
        surface: 63,
        pieces: 3,
        dpe: "A",
        chauffage: "Electrique",
        depotGarantie: 852,
        parking: true,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Contacté",
        datePublication: "2026-02-05",
        dateContact: "2026-02-12",
        dateVisite: "",
        contact: "",
        tel: "",
        adresse: "95 Rue Topaze",
        siteWeb: "https://www.bienici.com/annonce/location/montpellier/appartement/3pieces/hektor-progest3450-1297",
        notes: ""
    },
    {
        id: 32,
        quartier: "La Martelle",
        type: "T3",
        meublé: false,
        loyer: 912,
        charges: 0,
        charges_annuelles: 0,
        surface: 67,
        pieces: 3,
        dpe: "A",
        chauffage: "Electrique",
        depotGarantie: 912,
        parking: true,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Contacté",
        datePublication: "2026-02-11",
        dateContact: "2026-02-12",
        dateVisite: "",
        contact: "Agence Immobilière",
        tel: "0 48 25 31 10 4",
        adresse: "401 Avenue de Monsieur Teste",
        siteWeb: "https://fr.foncia.com/location/montpellier-34/appartement/331646377.htm?utm_source=jinka&utm_medium=app&utm_campaign=test",
        notes: ""
    },
    {
        id: 33,
        quartier: "Hopitaux-Facultés",
        type: "T3",
        meublé: false,
        loyer: 985,
        charges: 0,
        charges_annuelles: 0,
        surface: 71,
        pieces: 3,
        dpe: "D",
        chauffage: "Electrique",
        depotGarantie: 985,
        parking: true,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Contacté",
        datePublication: "2026-02-12",
        dateContact: "2026-02-12",
        dateVisite: "",
        contact: "Foncia Montpellier",
        tel: "0 48 25 31 10 4",
        adresse: "",
        siteWeb: "https://fr.foncia.com/location/montpellier-34/appartement/331646397.htm?utm_source=jinka&utm_medium=app&utm_campaign=test",
        notes: ""
    },
    {
        id: 34,
        quartier: "Lemasson",
        type: "T3",
        meublé: true,
        loyer: 990,
        charges: 0,
        charges_annuelles: 0,
        surface: 70,
        pieces: 3,
        dpe: "D",
        chauffage: "Electrique",
        depotGarantie: 990,
        parking: true,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Contacté",
        datePublication: "2026-02-10",
        dateContact: "2026-02-12",
        dateVisite: "",
        contact: "",
        tel: "",
        adresse: "",
        siteWeb: "https://www.orpi.com/annonce-location-appartement-t3-montpellier-34070-a4eaa744-eb0b-4e21-b6a5-e8c5efcff212/",
        notes: ""
    },
    {
        id: 35,
        quartier: "Aiguerelles",
        type: "T2",
        meublé: true,
        loyer: 909,
        charges: 0,
        charges_annuelles: 0,
        surface: 64,
        pieces: 2,
        dpe: "D",
        chauffage: "Electrique",
        depotGarantie: 909,
        parking: false,
        cave: false,
        terrasse: true,
        clim: true,
        ascenseur: false,
        balcon: false,
        etat: "Nouveau",
        datePublication: "2026-02-14",
        dateContact: "",
        dateVisite: "",
        contact: "",
        tel: "0 46 75 00 90 0",
        adresse: "",
        siteWeb: "https://immobilier.lefigaro.fr/annonces/annonce-97734347.html",
        notes: ""
    },
    {
        id: 36,
        quartier: "La Chambrete",
        type: "T3",
        meublé: false,
        loyer: 985,
        charges: 0,
        charges_annuelles: 0,
        surface: 69,
        pieces: 3,
        dpe: "D",
        chauffage: "Electrique",
        depotGarantie: 985,
        parking: false,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Contacté",
        datePublication: "2026-02-12",
        dateContact: "2026-02-12",
        dateVisite: "",
        contact: "",
        tel: "",
        adresse: "728 Rue de Fontcarrade",
        siteWeb: "https://immobilier.lefigaro.fr/annonces/annonce-94689043.html",
        notes: ""
    },
    {
        id: 37,
        quartier: "Figuerolles",
        type: "T2",
        meublé: true,
        loyer: 930,
        charges: 0,
        charges_annuelles: 0,
        surface: 64,
        pieces: 2,
        dpe: "D",
        chauffage: "Electrique",
        depotGarantie: 930,
        parking: true,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "En attente de rappel",
        datePublication: "2026-02-08",
        dateContact: "2026-02-12",
        dateVisite: "",
        contact: "Olivier V.",
        tel: "",
        adresse: "75 Rue de Fontcarrade",
        siteWeb: "https://www.paruvendu.fr/immobilier/location/appartement/1288447527A1KILHAP000",
        notes: "mail"
    },
    {
        id: 38,
        quartier: "Les Cevennes",
        type: "T3",
        meublé: false,
        loyer: 985,
        charges: 0,
        charges_annuelles: 0,
        surface: 67,
        pieces: 3,
        dpe: "D",
        chauffage: "Electrique",
        depotGarantie: 985,
        parking: true,
        cave: true,
        terrasse: true,
        clim: true,
        ascenseur: false,
        balcon: false,
        etat: "Rendez-vous visite",
        datePublication: "2026-02-13",
        dateContact: "2026-02-13",
        dateVisite: "2026-02-18",
        contact: "location@agenceducourreau.fr",
        tel: "467020717",
        adresse: "728 Rue de Fontcarrade",
        siteWeb: "https://www.agenceducourreau.fr/location/1-montpellier/appartement/t3/11387-f3-de-68-66-m-avec-terrasse-et-climatisation/",
        notes: ""
    },
    {
        id: 39,
        quartier: "Lemasson",
        type: "T3",
        meublé: false,
        loyer: 801,
        charges: 0,
        charges_annuelles: 0,
        surface: 54,
        pieces: 3,
        dpe: "A",
        chauffage: "Electrique",
        depotGarantie: 801,
        parking: true,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Contacté",
        datePublication: "2026-02-13",
        dateContact: "2026-02-13",
        dateVisite: "",
        contact: "l.briens@egerimconseil.com",
        tel: "0 46 75 44 28 4",
        adresse: "15 Rue de la Costa Brava",
        siteWeb: "",
        notes: ""
    },
    {
        id: 40,
        quartier: "Beaux-arts",
        type: "T4",
        meublé: true,
        loyer: 990,
        charges: 0,
        charges_annuelles: 0,
        surface: 66,
        pieces: 4,
        dpe: "F",
        chauffage: "Gaz",
        depotGarantie: 990,
        parking: false,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "En attente de rappel",
        datePublication: "2026-02-12",
        dateContact: "2026-02-12",
        dateVisite: "",
        contact: "orpi",
        tel: "0 48 77 43 46 4",
        adresse: "42 Avenue Saint-Lazare",
        siteWeb: "https://immobilier.lefigaro.fr/annonces/annonce-94619435.html",
        notes: "mail"
    },
    {
        id: 41,
        quartier: "Gambetta",
        type: "T3",
        meublé: false,
        loyer: 940,
        charges: 0,
        charges_annuelles: 0,
        surface: 62,
        pieces: 3,
        dpe: "E",
        chauffage: "Electrique",
        depotGarantie: 940,
        parking: false,
        cave: false,
        terrasse: false,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Nouveau",
        datePublication: "2026-02-07",
        dateContact: "",
        dateVisite: "",
        contact: "Agence du courreau - OUCHENE Yanis",
        tel: "0 42 34 73 14 2",
        adresse: "1 Bis Rue Adam de Craponne",
        siteWeb: "https://www.bienici.com/annonce/location/montpellier/appartement/3pieces/hektor-AGENCEDUCOURREAU-34000-11600",
        notes: "pas visale"
    },
    {
        id: 42,
        quartier: "Aiguelongue",
        type: "T3",
        meublé: false,
        loyer: 834,
        charges: 0,
        charges_annuelles: 0,
        surface: 55,
        pieces: 3,
        dpe: "C",
        chauffage: "Gaz",
        depotGarantie: 834,
        parking: false,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "En attente de rappel",
        datePublication: "2026-02-13",
        dateContact: "",
        dateVisite: "",
        contact: "",
        tel: "",
        adresse: "",
        siteWeb: "https://www.bienici.com/annonce/netty-fdiservicesimmo-appt-5302",
        notes: "Duplex. mail"
    },
    {
        id: 43,
        quartier: "Beaux-arts",
        type: "T3",
        meublé: false,
        loyer: 916,
        charges: 0,
        charges_annuelles: 0,
        surface: 59,
        pieces: 3,
        dpe: "C",
        chauffage: "Electrique",
        depotGarantie: 916,
        parking: true,
        cave: false,
        terrasse: true,
        clim: true,
        ascenseur: false,
        balcon: false,
        etat: "En attente de rappel",
        datePublication: "2026-02-11",
        dateContact: "2026-02-12",
        dateVisite: "",
        contact: "URBAN IMMOBILIER",
        tel: "0 78 09 77 43 9",
        adresse: "78 Avenue de Castelnau",
        siteWeb: "https://www.jinka.fr/ad/c2b0c8ee-9c0a-4d02-af17-994fc88bc7a0?alert_result=4960037521",
        notes: "mail"
    },
    {
        id: 44,
        quartier: "Hopitaux-Facultés",
        type: "T3",
        meublé: true,
        loyer: 845,
        charges: 0,
        charges_annuelles: 0,
        surface: 54,
        pieces: 3,
        dpe: "C",
        chauffage: "Electrique",
        depotGarantie: 845,
        parking: true,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Contacté",
        datePublication: "2026-02-12",
        dateContact: "2026-02-12",
        dateVisite: "",
        contact: "orpi",
        tel: "0 48 77 43 46 4",
        adresse: "55 Rue Chico Mendès",
        siteWeb: "https://immobilier.lefigaro.fr/annonces/annonce-78804692.html",
        notes: ""
    },
    {
        id: 45,
        quartier: "Croix d'Argent",
        type: "T3",
        meublé: false,
        loyer: 985,
        charges: 0,
        charges_annuelles: 0,
        surface: 62,
        pieces: 3,
        dpe: "A",
        chauffage: "Electrique",
        depotGarantie: 985,
        parking: true,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Contacté",
        datePublication: "2026-02-10",
        dateContact: "2026-02-12",
        dateVisite: "",
        contact: "Foncia Montpellier",
        tel: "0 48 25 31 10 4",
        adresse: "178 Rue de la Madeleine",
        siteWeb: "https://fr.foncia.com/location/montpellier-34/appartement/331634671.htm?utm_source=jinka&utm_medium=app&utm_campaign=test",
        notes: ""
    },
    {
        id: 46,
        quartier: "Estanove",
        type: "T2",
        meublé: false,
        loyer: 742,
        charges: 0,
        charges_annuelles: 0,
        surface: 46,
        pieces: 2,
        dpe: "E",
        chauffage: "Electrique",
        depotGarantie: 742,
        parking: false,
        cave: true,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Contacté",
        datePublication: "2026-02-12",
        dateContact: "2026-02-12",
        dateVisite: "",
        contact: "Ma Maison au Sud",
        tel: "0 61 85 95 45 2",
        adresse: "",
        siteWeb: "https://www.jinka.fr/ad/c660a2a1-1348-45f6-b87c-a81a01112737?alert_result=4968378806",
        notes: ""
    },
    {
        id: 47,
        quartier: "Estanove",
        type: "T2",
        meublé: false,
        loyer: 742,
        charges: 0,
        charges_annuelles: 0,
        surface: 45,
        pieces: 2,
        dpe: "E",
        chauffage: "Gaz",
        depotGarantie: 742,
        parking: true,
        cave: true,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Contacté",
        datePublication: "2026-02-13",
        dateContact: "2026-02-13",
        dateVisite: "",
        contact: "location@piergest.com",
        tel: "",
        adresse: "107 Rue Jacques Tati",
        siteWeb: "http://www.mamaisonausud.fr/fr/detail.htm?cle=345644011&monnaie=2",
        notes: ""
    },
    {
        id: 48,
        quartier: "Ovalie",
        type: "T2",
        meublé: false,
        loyer: 699,
        charges: 0,
        charges_annuelles: 0,
        surface: 42,
        pieces: 2,
        dpe: "B",
        chauffage: "Electrique",
        depotGarantie: 699,
        parking: true,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Contacté",
        datePublication: "2026-02-13",
        dateContact: "2026-02-13",
        dateVisite: "",
        contact: "l.briens@egerimconseil.com",
        tel: "0 46 75 44 28 4",
        adresse: "2530 Boulevard Paul Valéry",
        siteWeb: "",
        notes: ""
    },
    {
        id: 49,
        quartier: "Port Marianne",
        type: "T2",
        meublé: true,
        loyer: 776,
        charges: 0,
        charges_annuelles: 0,
        surface: 46,
        pieces: 2,
        dpe: "C",
        chauffage: "Electrique",
        depotGarantie: 776,
        parking: true,
        cave: true,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "En attente de rappel",
        datePublication: "2026-02-10",
        dateContact: "2026-02-12",
        dateVisite: "",
        contact: "AGENCE AIGUE MARINE IMMOBILIER L'ADRESSE",
        tel: "0 46 75 64 33 3",
        adresse: "6 Rue des Augustins",
        siteWeb: "https://immobilier.lefigaro.fr/annonces/annonce-75189402.html",
        notes: "mail"
    },
    {
        id: 50,
        quartier: "Aiguelongue",
        type: "T3",
        meublé: false,
        loyer: 905,
        charges: 0,
        charges_annuelles: 0,
        surface: 53,
        pieces: 3,
        dpe: "B",
        chauffage: "Electrique",
        depotGarantie: 905,
        parking: true,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Contacté",
        datePublication: "2026-02-04",
        dateContact: "2026-02-12",
        dateVisite: "",
        contact: "Foncia Montpellier",
        tel: "0 48 25 31 10 4",
        adresse: "586 Avenue du Val de Montferrand",
        siteWeb: "https://fr.foncia.com/location/montpellier-34/appartement/331648003.htm?utm_source=jinka&utm_medium=app&utm_campaign=test",
        notes: ""
    },
    {
        id: 51,
        quartier: "Figuerolles",
        type: "T3",
        meublé: false,
        loyer: 952,
        charges: 0,
        charges_annuelles: 0,
        surface: 55,
        pieces: 3,
        dpe: "C",
        chauffage: "Electrique",
        depotGarantie: 952,
        parking: true,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Refusé",
        datePublication: "2026-02-14",
        dateContact: "",
        dateVisite: "",
        contact: "Orpi - CPIMMO",
        tel: "0 48 77 43 46 4",
        adresse: "",
        siteWeb: "https://immobilier.lefigaro.fr/annonces/annonce-63811528.html",
        notes: "refus cdd"
    },
    {
        id: 52,
        quartier: "La Pompignane",
        type: "T2",
        meublé: false,
        loyer: 715,
        charges: 0,
        charges_annuelles: 0,
        surface: 41,
        pieces: 2,
        dpe: "A",
        chauffage: "Electrique",
        depotGarantie: 715,
        parking: true,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "En attente de rappel",
        datePublication: "2026-02-12",
        dateContact: "2026-02-12",
        dateVisite: "",
        contact: "URBAN IMMOBILIER",
        tel: "0 78 09 77 43 9",
        adresse: "200 Avenue Alphonse Juin",
        siteWeb: "https://www.jinka.fr/ad/72221e4f-8b67-4811-9f3b-6ec95fe15c5a?alert_result=4970759178",
        notes: "mail"
    },
    {
        id: 53,
        quartier: "Saint-Martin",
        type: "T3",
        meublé: true,
        loyer: 824,
        charges: 0,
        charges_annuelles: 0,
        surface: 47,
        pieces: 3,
        dpe: "D",
        chauffage: "Electrique",
        depotGarantie: 824,
        parking: false,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Refusé",
        datePublication: "2026-02-15",
        dateContact: "2026-02-15",
        dateVisite: "",
        contact: "",
        tel: "",
        adresse: "1 Rue des Primevères",
        siteWeb: "https://gensdeconfiance.com/fr/ui/post/realestate__rent/ac2100c9-fb50-4dfa-963f-a7f75eb0c238",
        notes: "plus dispo"
    },
    {
        id: 54,
        quartier: "Boutonnet",
        type: "T2",
        meublé: true,
        loyer: 799,
        charges: 0,
        charges_annuelles: 0,
        surface: 45,
        pieces: 2,
        dpe: "D",
        chauffage: "Gaz",
        depotGarantie: 799,
        parking: false,
        cave: false,
        terrasse: false,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Contacté",
        datePublication: "2026-02-01",
        dateContact: "",
        dateVisite: "",
        contact: "marjorie garcia",
        tel: "422614128",
        adresse: "",
        siteWeb: "https://www.bienici.com/annonce/century-21-202_3395_2350",
        notes: "viadomitia.location@century21.fr Dossier"
    },
    {
        id: 55,
        quartier: "Port Marianne",
        type: "T2",
        meublé: true,
        loyer: 900,
        charges: 0,
        charges_annuelles: 0,
        surface: 49,
        pieces: 2,
        dpe: "C",
        chauffage: "Gaz",
        depotGarantie: 900,
        parking: true,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Contacté",
        datePublication: "2026-01-23",
        dateContact: "2026-02-12",
        dateVisite: "",
        contact: "",
        tel: "499772630",
        adresse: "",
        siteWeb: "https://www.laforet.com/agence-immobiliere/castelnau/louer/montpellier/appartement-2-pieces-4716757",
        notes: "déposer dossier avec justif école sur site"
    },
    {
        id: 56,
        quartier: "Aiguelongue",
        type: "T2",
        meublé: false,
        loyer: 868,
        charges: 0,
        charges_annuelles: 0,
        surface: 46,
        pieces: 2,
        dpe: "A",
        chauffage: "Electrique",
        depotGarantie: 868,
        parking: false,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Contacté",
        datePublication: "2026-02-04",
        dateContact: "2026-02-12",
        dateVisite: "",
        contact: "Foncia Montpellier",
        tel: "0 48 25 31 10 4",
        adresse: "725 Rue du Pioch de Boutonnet",
        siteWeb: "https://fr.foncia.com/location/montpellier-34/appartement/331641511.htm?utm_source=jinka&utm_medium=app&utm_campaign=test",
        notes: ""
    },
    {
        id: 57,
        quartier: "Estanove",
        type: "T2",
        meublé: true,
        loyer: 789,
        charges: 0,
        charges_annuelles: 0,
        surface: 41,
        pieces: 2,
        dpe: "A",
        chauffage: "Gaz",
        depotGarantie: 789,
        parking: true,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Contacté",
        datePublication: "2026-02-12",
        dateContact: "2026-02-12",
        dateVisite: "",
        contact: "ELYADE SERVICES IMMOBILIERS",
        tel: "0 97 23 91 39 0",
        adresse: "",
        siteWeb: "https://www.bienici.com/annonce/seiitra-elyade_bi-25429",
        notes: ""
    },
    {
        id: 58,
        quartier: "Castelnau-le-lez",
        type: "T2",
        meublé: false,
        loyer: 842,
        charges: 0,
        charges_annuelles: 0,
        surface: 43,
        pieces: 2,
        dpe: "D",
        chauffage: "Electrique",
        depotGarantie: 842,
        parking: true,
        cave: false,
        terrasse: true,
        clim: true,
        ascenseur: false,
        balcon: false,
        etat: "Contacté",
        datePublication: "2026-02-11",
        dateContact: "2026-02-12",
        dateVisite: "",
        contact: "FRANCES IMMOBILIER",
        tel: "0 46 76 62 41 1",
        adresse: "169 Chem. des Thermes",
        siteWeb: "https://www.jinka.fr/ad/e7686188-ab85-4dad-a60c-11912cbbbe18?alert_result=4965909388",
        notes: ""
    },
    {
        id: 59,
        quartier: "Port Marianne",
        type: "T2",
        meublé: true,
        loyer: 940,
        charges: 0,
        charges_annuelles: 0,
        surface: 48,
        pieces: 2,
        dpe: "C",
        chauffage: "Electrique",
        depotGarantie: 940,
        parking: true,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Contacté",
        datePublication: "2026-02-12",
        dateContact: "2026-02-12",
        dateVisite: "",
        contact: "RESEAU IMMO DIFFUSION",
        tel: "0 97 45 31 38 1",
        adresse: "173 Av. des Droits de l'Homme",
        siteWeb: "https://www.jinka.fr/ad/3f787585-9b8c-4424-a53d-49ae39a7dcc8?alert_result=4967936398",
        notes: ""
    },
    {
        id: 60,
        quartier: "Boutonnet",
        type: "T2",
        meublé: false,
        loyer: 1000,
        charges: 0,
        charges_annuelles: 0,
        surface: 51,
        pieces: 2,
        dpe: "C",
        chauffage: "Electrique",
        depotGarantie: 1000,
        parking: true,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Nouveau",
        datePublication: "2026-02-12",
        dateContact: "",
        dateVisite: "",
        contact: "LES PYRAMIDES IMMOBILIER",
        tel: "0 46 75 67 15 0",
        adresse: "",
        siteWeb: "https://www.jinka.fr/ad/d5ce81ec-0ae0-4337-9e2b-139560b94c10?alert_result=4977761416",
        notes: ""
    },
    {
        id: 61,
        quartier: "Gambetta",
        type: "T2",
        meublé: true,
        loyer: 900,
        charges: 0,
        charges_annuelles: 0,
        surface: 44,
        pieces: 2,
        dpe: "C",
        chauffage: "Electrique",
        depotGarantie: 900,
        parking: false,
        cave: false,
        terrasse: false,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Contacté",
        datePublication: "2026-02-11",
        dateContact: "2026-02-12",
        dateVisite: "",
        contact: "MPL IMMO",
        tel: "",
        adresse: "",
        siteWeb: "https://www.jinka.fr/ad/8be50852-480d-412b-b3f1-db56a56b2071?alert_result=4965973971",
        notes: "mail envoyé via jinka pour visale ok"
    },
    {
        id: 62,
        quartier: "Port Marianne",
        type: "T2",
        meublé: true,
        loyer: 762,
        charges: 0,
        charges_annuelles: 0,
        surface: 37,
        pieces: 2,
        dpe: "A",
        chauffage: "Electrique",
        depotGarantie: 762,
        parking: true,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Nouveau",
        datePublication: "2026-02-03",
        dateContact: "",
        dateVisite: "",
        contact: "",
        tel: "0 18 76 53 27 4",
        adresse: "",
        siteWeb: "https://www.bienici.com/annonce/location/montpellier/appartement/2pieces/ag920875-511731980",
        notes: "demande si visale ok via chatbot"
    },
    {
        id: 63,
        quartier: "Beaux-arts",
        type: "T2",
        meublé: true,
        loyer: 769,
        charges: 0,
        charges_annuelles: 0,
        surface: 37,
        pieces: 2,
        dpe: "C",
        chauffage: "Electrique",
        depotGarantie: 769,
        parking: true,
        cave: false,
        terrasse: true,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Nouveau",
        datePublication: "2026-02-12",
        dateContact: "",
        dateVisite: "",
        contact: "",
        tel: "0 46 54 10 57 9",
        adresse: "",
        siteWeb: "https://www.bienici.com/annonce/adapt-immo-343737102",
        notes: "pas de visale"
    }
];

// Fonction pour charger les données selon le mode
function loadData(mode = 'achat') {
    const key = mode === 'location' ? 'appartements_location' : 'appartements_achat';
    const stored = localStorage.getItem(key);
    if (stored) {
        return JSON.parse(stored);
    }
    // Données à charger au premier lancement
    const sampleData = mode === 'location' ? sampleDataLocationReal : sampleDataAchat;
    localStorage.setItem(key, JSON.stringify(sampleData));
    return sampleData;
}

// Fonction pour sauvegarder les données selon le mode
function saveData(data, mode = 'achat') {
    const key = mode === 'location' ? 'appartements_location' : 'appartements_achat';
    localStorage.setItem(key, JSON.stringify(data));
}
