// Données de test pour le dashboard appartement
// Ces données sont chargées au démarrage si localStorage est vide

const sampleData = [
    {
        id: 1,
        quartier: "Centre-ville",
        type: "T2",
        prix: 125000,
        surface: 45,
        pieces: 2,
        dpe: "D",
        chauffage: "Électrique",
        charges: 1200,
        parking: true,
        cave: true,
        terrasse: false,
        clim: false,
        ascenseur: true,
        balcon: false,
        etat: "À voir",
        datePublication: "2024-01-15",
        dateContact: "2024-01-16",
        dateVisite: "2024-01-20",
        contact: "Agence Immo Sud",
        tel: "04 67 00 00 00",
        adresse: "12 Rue de la République",
        siteWeb: "https://www.example.com/bien1",
        notes: "Bien situé, proche commerces. Cuisine à refaire."
    },
    {
        id: 2,
        quartier: "Antigone",
        type: "T3",
        prix: 185000,
        surface: 65,
        pieces: 3,
        dpe: "C",
        chauffage: "Gaz",
        charges: 1500,
        parking: false,
        cave: true,
        terrasse: true,
        clim: false,
        ascenseur: true,
        balcon: false,
        etat: "Vu",
        datePublication: "2024-01-10",
        dateContact: "2024-01-11",
        dateVisite: "2024-01-18",
        contact: "Propriétaire",
        tel: "06 12 34 56 78",
        adresse: "Bâtiment C3, Avenue Picasso",
        siteWeb: "",
        notes: "Quartier calme, architecture moderne. Terrasse de 12m²."
    },
    {
        id: 3,
        quartier: "Comédie",
        type: "T2",
        prix: 165000,
        surface: 50,
        pieces: 2,
        dpe: "E",
        chauffage: "Électrique",
        charges: 900,
        parking: false,
        cave: false,
        terrasse: false,
        clim: false,
        ascenseur: false,
        balcon: true,
        etat: "Retenu",
        datePublication: "2024-01-12",
        dateContact: "2024-01-13",
        dateVisite: "2024-01-19",
        contact: "Agence Centre",
        tel: "04 67 11 11 11",
        adresse: "8 Rue de la Loge",
        siteWeb: "https://www.example.com/bien3",
        notes: "Emplacement idéal, balcon donnant cour intérieure. Travaux à prévoir."
    },
    {
        id: 4,
        quartier: "Ecusson",
        type: "Studio",
        prix: 95000,
        surface: 25,
        pieces: 1,
        dpe: "F",
        chauffage: "Électrique",
        charges: 600,
        parking: false,
        cave: false,
        terrasse: false,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Refusé",
        datePublication: "2024-01-08",
        dateContact: "2024-01-09",
        dateVisite: "2024-01-15",
        contact: "Agence Vieux",
        tel: "04 67 22 22 22",
        adresse: "3 Rue Jean-Jaurès",
        siteWeb: "",
        notes: "Trop petit, mauvaise isolation thermique. DPE défavorable."
    },
    {
        id: 5,
        quartier: "Port Marianne",
        type: "T4",
        prix: 245000,
        surface: 85,
        pieces: 4,
        dpe: "B",
        chauffage: "Pompe à chaleur",
        charges: 1800,
        parking: true,
        cave: true,
        terrasse: true,
        clim: true,
        ascenseur: true,
        balcon: false,
        etat: "À voir",
        datePublication: "2024-01-18",
        dateContact: "2024-01-19",
        dateVisite: "",
        contact: "Promoteur Neuf",
        tel: "04 67 33 33 33",
        adresse: "Rue de Berlin",
        siteWeb: "https://www.example.com/bien5",
        notes: "Neuf, label BBC. Terrasse de 20m². Parking inclus."
    },
    {
        id: 6,
        quartier: "Coursan",
        type: "Duplex",
        prix: 195000,
        surface: 75,
        pieces: 4,
        dpe: "C",
        chauffage: "Bois",
        charges: 800,
        parking: true,
        cave: true,
        terrasse: false,
        clim: false,
        ascenseur: false,
        balcon: false,
        etat: "Vu",
        datePublication: "2024-01-14",
        dateContact: "2024-01-15",
        dateVisite: "2024-01-21",
        contact: "Propriétaire",
        tel: "06 98 76 54 32",
        adresse: "15 Avenue de la Mairie",
        siteWeb: "",
        notes: "Duplex T4, bien agencé. Chauffage bois économique. Quartier calme."
    },
    {
        id: 7,
        quartier: "Beaux-Arts",
        type: "T3",
        prix: 210000,
        surface: 60,
        pieces: 3,
        dpe: "D",
        chauffage: "Gaz",
        charges: 1400,
        parking: false,
        cave: true,
        terrasse: false,
        clim: false,
        ascenseur: true,
        balcon: true,
        etat: "Retenu",
        datePublication: "2024-01-16",
        dateContact: "2024-01-17",
        dateVisite: "2024-01-22",
        contact: "Agence Artistes",
        tel: "04 67 44 44 44",
        adresse: "22 Rue des Écoles",
        siteWeb: "https://www.example.com/bien7",
        notes: "Quartier étudiant, proche tram. Hauts plafonds, moulures."
    },
    {
        id: 8,
        quartier: "Polygone",
        type: "T2",
        prix: 140000,
        surface: 48,
        pieces: 2,
        dpe: "E",
        chauffage: "Électrique",
        charges: 1100,
        parking: false,
        cave: false,
        terrasse: false,
        clim: false,
        ascenseur: true,
        balcon: false,
        etat: "Refusé",
        datePublication: "2024-01-11",
        dateContact: "2024-01-12",
        dateVisite: "2024-01-17",
        contact: "Agence Commerciale",
        tel: "04 67 55 55 55",
        adresse: "Boulevard d'Occitanie",
        siteWeb: "",
        notes: "Trop bruyant, orientation Nord. Prix au m² élevé."
    },
    {
        id: 9,
        quartier: "Figuerolles",
        type: "T3",
        prix: 155000,
        surface: 62,
        pieces: 3,
        dpe: "D",
        chauffage: "Collectif",
        charges: 1300,
        parking: true,
        cave: true,
        terrasse: false,
        clim: false,
        ascenseur: true,
        balcon: true,
        etat: "À voir",
        datePublication: "2024-01-19",
        dateContact: "2024-01-20",
        dateVisite: "",
        contact: "Agence Nord",
        tel: "04 67 66 66 66",
        adresse: "Avenue de Figuerolles",
        siteWeb: "https://www.example.com/bien9",
        notes: "Quartier résidentiel, proche écoles. Parking privatif."
    },
    {
        id: 10,
        quartier: "Gambetta",
        type: "T4",
        prix: 225000,
        surface: 80,
        pieces: 4,
        dpe: "C",
        chauffage: "Gaz",
        charges: 1600,
        parking: true,
        cave: true,
        terrasse: false,
        clim: false,
        ascenseur: true,
        balcon: true,
        etat: "Vu",
        datePublication: "2024-01-13",
        dateContact: "2024-01-14",
        dateVisite: "2024-01-20",
        contact: "Agence Gambetta",
        tel: "04 67 77 77 77",
        adresse: "Boulevard Gambetta",
        siteWeb: "",
        notes: "Appartement lumineux, balcon traversant. Bon plan."
    }
];

// Fonction pour charger les données
function loadData() {
    const stored = localStorage.getItem('appartements');
    if (stored) {
        return JSON.parse(stored);
    }
    // Si aucune donnée stockée, utiliser les données de test
    localStorage.setItem('appartements', JSON.stringify(sampleData));
    return sampleData;
}

// Fonction pour sauvegarder les données
function saveData(data) {
    localStorage.setItem('appartements', JSON.stringify(data));
}
